### ISSUE TITLE
Request: Reading data from blk.dat files

### ISSUE THREAD

**Issue by asher-lab** [hacash/core#1]
Is there a program which read ```blk.dat``` files from ```hacash_mainnet_data```

I found a method to read those binary files and convert them into readable format. [https://github.com/mrqc/bitcoin-blk-file-reader]. However as I browser up for transactions using this method and tried searching it into the explorer, data are not found. 

Is there a way to read blk.dat files? If I am correct, I need to modify some part of ```analyze.py``` to make it compatible to Hacash?

**Comment by asher-lab** [comment]
https://github.com/asher-lab/Hacash-Block-Reader

**Comment by jojoin** [comment]
rpc api are already on the way to development. You don't need to analyze data files stored on disk directly.

**Comment by asher-lab** [comment]
Thank You

**Comment by jojoin** [comment]
RPC  API doc:   https://github.com/hacash/service/blob/master/rpc_api_doc.cn.md
